#!/usr/bin/env sh

set -x

baseurl='https://www.duckdns.org/update?domains=%s&token=%s&txt=&clear=True%s'
test "$(printf "url=$baseurl\n" "$DUCKDNS_DOMAIN" "$DUCKDNS_TOKEN" "$CERTBOT_VALIDATION" | curl -K -)" = 'OK'
