#!/usr/bin/env sh

echo "certbot txt record: $CERTBOT_VALIDATION"

baseurl='https://www.duckdns.org/update?domains=%s&token=%s&txt=%s'
result="$(printf "url=$baseurl\n" "$DUCKDNS_DOMAIN" "$DUCKDNS_TOKEN" "$CERTBOT_VALIDATION" | curl -K -)"

# give some time for the record to update
echo "waiting for txt record"
for i in $(seq 0 60); do
    val="$(nslookup -type=TXT "$DUCKDNS_DOMAIN.duckdns.org" | grep "$DUCKDNS_DOMAIN.duckdns.org.*text.*=.*" | sed -n 's/.*"\([^"]*\)".*/\1/p')"
    echo "current txt record: $val"
    test "$val" = "$CERTBOT_VALIDATION" && break
    sleep 10
done

echo "waiting 60s for propagation"
sleep 60
test "$result" = 'OK'
