#!/usr/bin/env sh

certbot certonly --manual --preferred-challenges dns-01 --keep \
    --email="$LE_EMAIL" --domains="$DUCKDNS_DOMAIN.duckdns.org" \
    --agree-tos --no-eff-email --manual-public-ip-logging-ok \
    --manual-auth-hook=certbot-auth --manual-cleanup-hook=certbot-cleanup \
    "$@"

certbot certonly --manual --preferred-challenges dns-01 --keep \
    --email="$LE_EMAIL" --domains="*.$DUCKDNS_DOMAIN.duckdns.org" \
    --agree-tos --no-eff-email --manual-public-ip-logging-ok \
    --manual-auth-hook=certbot-auth --manual-cleanup-hook=certbot-cleanup \
    "$@"

if [ -n "$COMMAND" ]; then
    /usr/bin/env sh -c "$COMMAND"
fi
