#!/usr/bin/env sh

set -x

logfile=/var/log/duckdns.log
baseurl='https://www.duckdns.org/update?domains=%s&token=%s&ip='
printf "url=$baseurl\n" "$DUCKDNS_DOMAIN" "$DUCKDNS_TOKEN" | curl -o "$logfile" -K -
